### ISSUE TITLE
Macro_inverted method not working?

### ISSUE THREAD

**Issue by Impeta** [JonathanNye/img2splat#1]
It works flawlessly with connecting my Switch into my computer through nxbt plus bluetooth, yet when I reach to this final part and do `sudo nxbt macro -c "splat_macro_inverted.txt" -r`, my Switch seems to not wanna leave out of the connecting controller pop-up. From the "click" sounds, I assume any button is pressed per nxbt command except A, hence so. Just gets stuck on this and won't move forward.

snip

At the same pace, my terminal output:
```
$ java -jar img2splat.jar splat3dd.png
Generated splat_macro.txt with 79034 operations.
Generated splat_macro_inverted.txt with 42680 operations.
Recommend using splat_macro_inverted.txt, which has 46.0% fewer operations.
If you're repairing after an initial run, stick to the same type you started with.
If you decide to use the inverted macro, don't forget to fill your canvas with black pixels before starting!
Woomy!
$ sudo nxbt macro -c "splat_macro_inverted.txt" -r
Creating controller...
Waiting for connection...
Connected!
Running macro...
```
Here's said .txt I'm inputting with: snip

For reference, this is the base image I wanna imprint. Did I do it correctly? It's on .png already (although converted from .jpg at first).
snip

Tried nxbt normal, then your own nxbt fork. Neither are much success (assuming I had to first install the vanilla nxbt first, then install your own fork on top of it).
Appreciate any input and help, by then!

**Comment by JonathanNye** [comment]
Sorry you're having trouble!

The macro assumes that controller connection window won't pop up, so it doesn't contain any commands to dismiss it. It's assumed that when you run the command, the Bluetooth controller will seamlessly connect with no interruption while you're on the Splatoon 3 post editor, which has been the case for me.

Does that controller connection window pop up after you start running the macro?
I forget what exact button presses you'd need to dismiss that window, but as a workaround, you might need to manually add the following commands at the _beginning_ of your generated macro to dismiss the popup:
```
3.0s
A 0.1s
```
Which just waits a moment, presses A to dismiss the popup, and the continues on as normal.

Hope that helps!

**Comment by Impeta** [comment]
Wow, quick reply. Nice! And no worries, just glad you're replying with care. :heart:

> The macro assumes that controller connection window won't pop up, so it doesn't contain any commands to dismiss it. It's assumed that when you run the command, the Bluetooth controller will seamlessly connect with no interruption while you're on the Splatoon 3 post editor, which has been the case for me.

Yeah, looks like an update or two on Nintendo's part has shuffled this a bit. Here, after I made the preparations already on drawing board and then input the command, the pop-up comes on and shows nxbt connecting to it after I run the macro, yes.

Funnily enough, I sort of grasped that was the exact solution to it before you would ever post! Adding `A 0.1s` in-between `3.0s` and `DPAD_DOWN 0.1s` indeed did the trick.
Though, I now get the occurrence of seeing my pixels being offset by one, conceding the inputs being skipped out, which then comes your forked nxbt in hopes to circumvent that. I'm a little dumb on this "pip" aspect, apologizes, so could you explain in better detail of how would I go about using your forked nxbt (and how can I purge off all pip packages to start anew)? Kindly thanks!

**Comment by JonathanNye** [comment]
Glad to hear you made some progress! I get errors similar to this as well. My theory is that, in addition to Bluetooth stack hiccups, sometimes Splatoon 3 _itself_ will also briefly lag, which there's not much we can do about. 😞 

As far as trying my NXBT fork... I'm not much of a `pip` expert either but basically you want to

1.  Clone the fork
2.  Point your shell to the root of the cloned project
3. Do `pip3 install -e .` If you already have nxbt installed, this should install over it.  
5. Confirm the fork is being used by running `pip3 list | grep nxbt`. It should spit out something like this:
   `nxbt                   0.1.4           local/path/to/cloned/fork`
    The last part there, the local path, is most important. If you're using the mainline version, that local path won't be there at all.

Cheers!

**Comment by Impeta** [comment]
>Glad to hear you made some progress! I get errors similar to this as well. My theory is that, in addition to Bluetooth stack hiccups, sometimes Splatoon 3 itself will also briefly lag, which there's not much we can do about. :disappointed:

I see. Still, I'm glad it does work flawlessly! I think that's mostly on Splatoon 3 itself and the locked thirty frames per second that's kind of incompatible with bluetooth, making it lose frames and thus skipping inputs.

Regardless, thanks for the instructions! Just wanted to be absolutely sure if I was doing it right. It does spits that I'm really using your fork, so yeah, it isn't anything on my end like I was dreading about. Your fork, while sadly doesn't fix it completely with few offset pixels still, does seem to perform overall better on imprinting. You might like update your README.md based on our findings here, specifying about including `A 0.1s` in macros and adding your more coherent steps on installing your fork.

Another question, sorry, but would you happen to know if nxbt depends on `bluez-utils-compat` or `bluez-utils`?  The former is latter plus deprecated tools, and I would like to switch to latter. I'm on Arch Linux.

**Comment by JonathanNye** [comment]
Sorry, I'm a bit out of my depth on the package manager stuff.

I was using Vagrant on Windows 10 -- nxbt has it tooled up to use `apt` to install bluez and it kind of ✨ just worked ✨  for me.

If you didn't have to pull in anything, your system probably already had bluez installed. It [doesn't seem like](https://archlinux.org/packages/extra/x86_64/bluez/) they'd pull in the `-compat` package by default.
