### ISSUE TITLE
Repair mode should delete the line automatically

### ISSUE THREAD

**Issue by zaventh** [JonathanNye/img2splat#2]
When repairing lines, code should be generated to simply delete the line first, thus avoiding having to do each one manually.

If I get the chance, I will PR this myself. But just wanted to open the discussion.

**Comment by JonathanNye** [comment]
Cool idea! Maybe I'll take a whack at it this weekend between Splatfest matches 😁

**Comment by JonathanNye** [comment]
@zaventh Gave it a shot, interested in your thoughts!
